INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is male / female friendship possible ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is death sentence sometimes acceptable ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Does euthanasia belong to civilised societies ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is human cloning ok ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Should marijuana be legal ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Religion does more harm than good ");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is beeing in love with a family member ok ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is a schizophrenic person who commit suicide a murderer ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever farted and blamed it on a pet ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever been drinking and driving ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever gone in public without a bra ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever thrown up on a perfect stranger ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever peed from a balcony ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is abortion a crime ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever pointed a gun at someone ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Would you eat a living cockroach for 1000$ ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "If you could start your life again with your current memories, would you do it ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is it ok to hit on someone while on a date with someone else ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Would you kill to protect your family ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever injected or swallowed hard drugs ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever cross-dressed ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever streaked ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Could you be attracted by someone of the same sex ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever gotten bullied ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever done something you could get a prison sentence for ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Do you believe in love at first sight ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you been spanked in the last 6 month ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "I have or plan to have a tattoo");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Would you hook up with a teacher ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Masturbating to anime is a normal thing");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is there magic in this world ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is it possible to predict the future ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever got / given a footjob ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever had foreplay while driving ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever burped on someone's face ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Would you try / Have you tried anal sex ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Have you ever hoped to have a chance with one of the players ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Is threesome (including your partner) cheating ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever thought of an ex-girlfriend / boyfriend during sex ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever masturbated in front of a mirror ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Is homosexuality a sickness ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Would you accept your child homosexuality ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Do you think it’s ok to drive after one spliff ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Could you be attracted by someone 20 years older than you ?");
INSERT INTO QUESTION(adult_only, text) VALUES(1, "Have you ever had sexual thoughts about your step mother / step father ?");
INSERT INTO QUESTION(adult_only, text) VALUES(0, "Do you agree with spanking as an educational tool ?");
